; platformio.ini

[env]
framework = arduino
monitor_speed = 115200
lib_deps = B:/SmartHomeSystem/src/SHScore
           B:/SmartHomeSystem/src/SHSlibrary/SHS_DHT
           B:/SmartHomeSystem/src/SHSsettings
           B:/SmartHomeSystem/src/SHSlibrary/SHS_SensorTypes
           https://github.com/GyverLibs/GyverIO.git
           https://github.com/GyverLibs/Random16.git
           https://github.com/adafruit/DHT-sensor-library.git
           https://github.com/GyverLibs/EncButton.git
           fastled/FastLED@^3.4.0
           
           
; lib_extra_dirs = ../../
    

[env:esp32]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = nodemcu-32s
upload_speed = 921600
monitor_speed = 115200
build_type = debug
board_build.filesystem = littlefs

[env:esp8266]
platform = espressif8266
framework = arduino
board = esp12e
upload_speed = 921600
monitor_speed = 115200
build_type = debug
board_build.filesystem = littlefs
build_flags = -D SHS_SF_DEBUG

